### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Dakarakoso** [Dakarakoso/clone-tabnews#27]
## Context
All data will be public
## Execution
With email and passwrod we create a session. All session will be stored in Postgres.
## tasks
- [ ] Install bcrypt
- [ ] Define sessions table
- [ ] Create an API route  for user registration
- [ ] Create an API route for user login
- [ ] Deal with session management
