### ISSUE TITLE
Email Service

### ISSUE THREAD

**Issue by Dakarakoso** [Dakarakoso/clone-tabnews#28]
## Context
Needs to send email to users. Verify if the email was sent correctly. Handle notifications based on email status.
## Execution
Use Docker to set up a MailCatcher service, which will capture and store emails within the machine for testing. Implement an orchestrator that will: Check the latest email sent, and clear the inbox for subsequent tests.
## Tasks
- [x] Set Up MailCatcher Service in Docker
- [x] Configure Node.js Email Module: node-mailer
- [x] Implement Orchestrator Module
- [x] Implement End-to-End (E2E) Tests
- [x] Integrate with CI/CD Pipeline(github actions)
