### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by Dakarakoso** [Dakarakoso/clone-tabnews#29]
## Context
Each user has unique, granular permissions. For example, a user who creates a table will start with limited permissions on that resource.
## Execution
Permissions are tied to specific resources rather than roles. Will be responsible for verifying permissions. Block access to specific endpoints, e.g., `/api/v1/migrations.`
## Tasks
- [x] Define Permissions Structure
- [x] Develop Middleware for Authorization
- [x] Implement Resource-Based Permission Assignment
- [x] Implement Endpoint Restrictions and Filters
- [x] Testing and Validation
- [x] Logging and Error Handling
